name: Docs

on: [push]

jobs:
  build_doc:

    # docfx in unity-runner is for v18
    runs-on: ubuntu-18.04

    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
    # Checkout
    - uses: actions/checkout@v2
    
    # Generate .sln
    - name: Activate license
      uses: James-Frowen/unity-runner@3.2.11
      with:
        entrypoint: /activate.sh
        
    - name: Generate Solution
      uses: James-Frowen/unity-runner@3.2.11
      with:
        # Arguments to pass to unity
        args: -buildTarget StandaloneWindows64 -customBuildName Mirage -customBuildPath ./build/StandaloneWindows64 -projectPath . -executeMethod  UnityEditor.SyncVS.SyncSolution -quit

    # Generate docs
    - name: Generate API
      uses: James-Frowen/unity-runner@3.2.11
      with:
        entrypoint: /docfx.sh
        args: metadata --logLevel verbose doc/docfx.json
    
    - name: Compile Docs
      uses: James-Frowen/unity-runner@3.2.11
      with:
        entrypoint: /docfx.sh
        args: build --logLevel verbose doc/docfx.json
    
    # Deploy to Github pages
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      if: github.ref == 'refs/heads/master'
      with:
        # Create incremental commit instead of doing push force
        keep_history: true
        # Allow an empty commit to be created
        allow_empty_commit: true
        jekyll: false
        # Build directory to deploy
        build_dir: doc/_site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
